### ISSUE TITLE
[demo_nodes_py] talker_qos and talker don't use the same topic name

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/demos#144]
We can either merge them into a single executable or make them use the same topic (same for listener)

**Comment by wjwwood** [comment]
Should they have the same topic?

File links:

- https://github.com/ros2/demos/blob/master/demo_nodes_py/topics/talker.py
- https://github.com/ros2/demos/blob/master/demo_nodes_py/topics/talker_qos.py

**Comment by Kukanani** [comment]
I was talking about this with @dhood, and we felt that it was perplexing to be able to run `talker`/`listener` and `talker_qos`/`listener_qos`, but not `talker_qos`/`listener` etc.

**Comment by Kukanani** [comment]
^ sorry, `talker_qos`/`listener` is not possible, but `talker`/`listener_qos` should be.

**Comment by mikaelarguedas** [comment]
It depends if we want talker to stay as minimal as possible or if we consider that the one in the examples repo serves that purpose. If the latter I think we should just make a single talker/listener that can take a `--reliable` (or a `--best-effort`) argument rather than maintaining 2 versions of it.
Otherwise just matching topic names is fine by me

**Comment by mikaelarguedas** [comment]
ok I settled with just making them use the same topic name for now https://github.com/ros2/demos/pull/142/commits/57a13a99c95f7e69cfaa1bfc05bb3ca655a817db
