### ISSUE TITLE
Windows binaries are built with debug symbols

### ISSUE THREAD

**Issue by esteve** [ros2/demos#19]

**Comment by esteve** [comment]
![dll_error](https://cloud.githubusercontent.com/assets/33620/9559890/43f75736-4db2-11e5-9602-5df976763c92.png)

**Comment by esteve** [comment]
Installing the VC++ redistributable didn't fix this:

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by mikaelarguedas** [comment]
Closing this because we haven't faced this in any of the previous release testing of windows binaries
