### ISSUE TITLE
allocator_tutorial publishes a message every millisecond, which floods the network

### ISSUE THREAD

**Issue by clalancette** [ros2/demos#250]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Bionic arm64
- Installation type:
  - Fat archive from 2018-06-21, downloaded from here: https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/475/artifact/ws/ros2-package-linux-aarch64.tar.bz2
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

As can be seen [here](https://github.com/ros2/demos/blob/b026e522ed9f8a6fba08497f34beeafa3975bccf/demo_nodes_cpp/src/topics/allocator_tutorial.cpp#L198), the `allocator_tutorial` publishes a message every millisecond.  This ends up flooding the network, which is a problem over wireless.  Is this test meant to stress the environment like this, or should we reduce this to publishing once every 10 or 100 milliseconds?

**Comment by dirk-thomas** [comment]
Addressed by #257.
