### ISSUE TITLE
[lifecycle] lifecycle_listener cannot transition

### ISSUE THREAD

**Issue by sloretz** [ros2/demos#303]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Bionic (amd64 and arm64)
- Installation type:
  - binaries and packaging job
- Version or commit hash:
  - crystal pre-release and https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/649/
- DDS implementation:
  - Fast-RTPS, Opensplice
- Client library (if applicable):
  - N/A 

#### Steps to reproduce issue

1. Start a lifecycle listener
   ```
   ros2 run lifecycle lifecycle_listener
   ```
1. Get the current state
   ```
   ros2 lifecycle get
   ```
1. List transitions for `lc_listener`
   ```
   ros2 lifecycle list /lc_listener
   ```

#### Expected behavior

Lifecycle listener state would be in `unconfigured` state. Listing should show two transitions: configure, shutdown.

#### Actual behavior

`ros2 lifecycel get` returns nothing. Listing transitions runs until SIGINT is sent.

#### Additional information
There don't appear to be any lifecycle services for the listener.

```bash
$ ros2 service --include-hidden-services list -t
/_ros2cli_node_daemon_0/describe_parameters [rcl_interfaces/DescribeParameters]
/_ros2cli_node_daemon_0/get_parameter_types [rcl_interfaces/GetParameterTypes]
/_ros2cli_node_daemon_0/get_parameters [rcl_interfaces/GetParameters]
/_ros2cli_node_daemon_0/list_parameters [rcl_interfaces/ListParameters]
/_ros2cli_node_daemon_0/set_parameters [rcl_interfaces/SetParameters]
/_ros2cli_node_daemon_0/set_parameters_atomically [rcl_interfaces/SetParametersAtomically]
/lc_listener/describe_parameters [rcl_interfaces/DescribeParameters]
/lc_listener/get_parameter_types [rcl_interfaces/GetParameterTypes]
/lc_listener/get_parameters [rcl_interfaces/GetParameters]
/lc_listener/list_parameters [rcl_interfaces/ListParameters]
/lc_listener/set_parameters [rcl_interfaces/SetParameters]
/lc_listener/set_parameters_atomically [rcl_interfaces/SetParametersAtomically]
```

**Comment by Karsten1987** [comment]
the lifecycle listener is a regular node, not a lifecycle node. Therefore it's by design not available.
