### ISSUE TITLE
Lifecycle Tutorial: Broken Recordings

### ISSUE THREAD

**Issue by davetcoleman** [ros2/demos#309]
@Karsten1987 Pretty minor feedback, but the way in which asciinema records were embedded in the [lifecycle tutorial](https://github.com/ros2/demos/blob/master/lifecycle/README.rst) seem to have expired per this [dead link](https://asciinema.org/a/e0f11qvpberltp8r1w04wzw9t):

> This recording has been archived
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by gonzodepedro** [comment]
This year asciinema started to archive unclaimed recordings.
