### ISSUE TITLE
Build failed on MSVC

### ISSUE THREAD

**Issue by chaplin89** [ros2/demos#312]
## Bug report

**Required Info:**

- Operating System:
Windows 10
- Installation type:
Binary
- Version or commit hash:
latest vesion (20190214 - Patch 2): bbf4dd1371df02b3f446dacd4bb4f6aed181db14
- DDS implementation:
eProsima’s Fast RTPS
- Client library (if applicable):
rclcpp

#### Steps to reproduce issue
```
call C:\dev\release\ros2-windows\local_setup.bat
git clone https://github.com/ros2/demos
cd demos
colcon build
```

#### Expected behavior
Every package compiles correctly
#### Actual behavior
Build fail with the following outcome:

```
Summary: 3 packages finished [42.2s]
  1 package failed: image_tools
  7 packages aborted: composition demo_nodes_cpp demo_nodes_cpp_native intra_process_demo pendulum_msgs rttest tlsf_cpp
  5 packages had stderr output: composition demo_nodes_cpp image_tools intra_process_demo pendulum_msgs
  5 packages not processed
```

[**Log files**](https://github.com/ros2/demos/files/2875190/build_2019-02-18_11-32-03.zip)

#### Additional information
What's the point with rttest?

The readme of pendolum_control says:

> 
> If you haven't already, clone rttest into your ament workspace.
> 
> Build your ament workspace:
> ./src/ament/ament_tools/scripts/ament.py build --symlink-install

What's my "ament workspace"?

Where I am supposed to find ament.py?

It seems to me that those instructions are for linux only.

**Comment by sloretz** [comment]
Hi @chaplin89 ,

The note about an `ament` workspace is outdated. It's not responsible for the build failure. The summary says `1 package failed: image_tools`. The `stderr.log` in the `image_tools` directory in the zip file says:

```
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
```

See [this page for OpenCV install instructions](https://index.ros.org/doc/ros2/Installation/Windows-Install-Binary/#install-opencv). For instructions on building ros2 from source on windows, see [this page](https://index.ros.org/doc/ros2/Installation/Windows-Development-Setup/).

I think the issue has been addressed, so I'll close this for now.
