### ISSUE TITLE
Update demos to use composition

### ISSUE THREAD

**Issue by jacobperron** [ros2/demos#325]
#### Feature description

Since it is the recommended way to write nodes as components, it would be good to refactor most, if not all, of the demos to be composable. This way new users learning from the demos will be exposed to best practices in ROS 2 development.

Since components are only available in C++, there is nothing to be done for the Python demos.

#### Implementation considerations

The [composition](https://github.com/ros2/demos/tree/0cb8fc5ff993820d33826d2de23fe81a3c8a4062/composition) package is a good place to look for examples of writing components.

**Comment by nuclearsandwich** [comment]
Can this be closed now that #375 is merged/
