### ISSUE TITLE
got a memory leak

### ISSUE THREAD

**Issue by zdy333666** [ros2/demos#340]
these code in files like  dummy_robot/**/*.cpp :
rclcpp::TimeSource ts(node);
rclcpp::Clock::SharedPtr clock = std::make_shared<rclcpp::Clock>(RCL_ROS_TIME);
ts.attachClock(clock);
in the while loop cause the memory leak, they should be put out of the where loop, and then, I tried it ok.

**Comment by jacobperron** [comment]
Thanks for reporting the issue. If you have time to open a PR with your proposed patch, it is appreciated :slightly_smiling_face:
