### ISSUE TITLE
action_tutorials Python Fibonacci Client/Server not executable

### ISSUE THREAD

**Issue by clalancette** [ros2/demos#341]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - 0.7.4 (0b54af7f83dd3aca000d04c6b69a2c25d1c09803)
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```
ros2 run action_tutorials fibonacci_action_server.py
```
or
```
ros2 run action_tutorials fibonacci_action_client.py
```

#### Expected behavior

Running action server or client.

#### Actual behavior

```
Traceback (most recent call last):
  File "/home/ubuntu/ros2_ws/install/ros2cli/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.7.0', 'console_scripts', 'ros2')()
  File "/home/ubuntu/ros2_ws/install/ros2cli/lib/python3.6/site-packages/ros2cli/cli.py", line 69, in main
    rc = extension.main(parser=parser, args=args)
  File "/home/ubuntu/ros2_ws/install/ros2run/lib/python3.6/site-packages/ros2run/command/run.py", line 72, in main
    return run_executable(path=path, argv=args.argv, prefix=prefix)
  File "/home/ubuntu/ros2_ws/install/ros2run/lib/python3.6/site-packages/ros2run/api/__init__.py", line 61, in run_executable
    process = subprocess.Popen(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ubuntu/ros2_ws/install/action_tutorials/lib/action_tutorials/fibonacci_action_server.py'
```

#### Additional information
Since this is called out in our Python action client [tutorial](https://index.ros.org/doc/ros2/Tutorials/Actions/Writing-an-Action-Client-Python/), we should probably fix this before Dashing.

**Comment by jacobperron** [comment]
Looks like the scripts are missing shebang lines.

**Comment by clalancette** [comment]
Shouldn't this be done with with the entry_points, though, similar to https://github.com/ros2/demos/blob/master/demo_nodes_py/setup.py#L34 ?

**Comment by jacobperron** [comment]
I'm not sure. I didn't see many examples of adding a `setup.py` alongside a CMake package. I can give it a try to see if it works.
