### ISSUE TITLE
Document that Fast-RTPS does not support QoS setting Liveliness

### ISSUE THREAD

**Issue by jacobperron** [ros2/demos#365]
#### Feature description

Document that QoS Liveliness is not supported by Fast-RTPS in the demo's README.

Otherwise, a user may unexpectedly run into the error:

```
libc++abi.dylib: terminating with uncaught exception of type rclcpp::exceptions::RCLError: could not create subscription: Liveliness QoS is not yet supported for fastrtps.
```

**Comment by mabelzhang** [comment]
+1
Ran into this while porting a node from ROS 1 to ROS 2.

**Comment by mabelzhang** [comment]
Closing as #387 has addressed this
