### ISSUE TITLE
Lifecycle Demo not working on Opensplice

### ISSUE THREAD

**Issue by claireyywang** [ros2/demos#414]
## Bug report

**Required Info:**

- Operating System:
  - OSX Mojave 
- Installation type:
  - from source 
- Version or commit hash:
  - Eloquent 
- DDS implementation:
  - Opensplice 
- Client library (if applicable):
  - N/A 

#### Steps to reproduce issue

```
ros2 launch lifecycle lifecycle_demo.launch.py
```
or in three terminal windows  
```
ros2 run lifecycle lifecycle_talker
```
```
ros2 run lifecycle lifecycle_listener
```
```
ros2 run lifecycle lifecycle_service_client
```

#### Expected behavior
Run as shown in demo https://github.com/ros2/demos/blob/master/lifecycle/README.rst#run-the-demo

#### Actual behavior
`Talker` process automatically exits, and `lifecycle_service_client` returns an error msg below 
```bash
[ERROR] [lc_client]: Server time out while getting current state for node lc_talker
```

**Comment by jacobperron** [comment]
Both Eloquent and Opensplice are no longer supported.
