### ISSUE TITLE
Use launch front-end for dummy_robot_bringup

### ISSUE THREAD

**Issue by jacobperron** [ros2/demos#434]
#### Feature description

As of Eloquent, we can use XML and YAML markup for launch scripts. I think it would be nice to launch scripts using one (or both) of the markup languages, that can replace or sit alongside the [existing launch file](https://github.com/ros2/demos/blob/master/dummy_robot/dummy_robot_bringup/launch/dummy_robot_bringup.launch.py).

**Comment by p-vega** [comment]
Hi @jacobperron I'd like to work on this issue.

**Comment by jacobperron** [comment]
@p-vega Great! Let me know if you have any questions.
