### ISSUE TITLE
[topic_monitor] wrong results with high publishing rate

### ISSUE THREAD

**Issue by eliasdc** [ros2/demos#460]
## Bug report

We are trying to monitor the performance of ros2 with respect to DDS implementation, lossy networks and varying payload size. We noticed that the results look very bad when we run the topic_monitor nodes with high publishing rates and we saw that the internal timers of the node can run out of sync showing a wrong results after a while.

Running the example below without the `--display` option increases the problem. The main thread is using up all the resources and the reception rate is much lower than the expected 100% on a local machine. When running with the `--display` option you can improve the reception rate by lowering the statics calculation interval `--stats-calc-period 0.01`.

Running the `topic_monitor` node for a while will result in the publishers and subscribers timer to go out of sync, systematically lowering the reception rate (until 0% is reached).

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - ab95bef2d44a952f1690acd872585ed9ad0f177b
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

Terminal 1 (publishing at 100Hz):
```
 ros2 run topic_monitor data_publisher -- --depth 1 --period 0.01 --best-effort
```

Terminal 2:
```
ros2 run topic_monitor topic_monitor --expected-period 0.01 --window-size 100 --stats-calc-period 1 --display
```
lowering `--stats-calc-period` increases the reception rate (which should not have any effect).
removing `--display` decreases the reception rate (which should not have any effect).

#### Expected behavior

For a 100Hz publication rate we expect a reception rate of 100% on a local machine.

#### Actual behavior

The main thread's loop affects the reception rate. For a 100Hz publication rate we see an reception rate of 60% with a stats calculation interval of 1 second. Lowering the stats calculation interval to 0.01s results in a reception rate of 100%.

#### Additional information

These problems have 2 causes: 

- python threading is used which is not multi core processing so if the main thread keeps working the background threads are not triggered enough.
- the expected value is entirely based on a timer inside the topic monitor node which is not always an exact clock. When receiving a message we can assume the next expected value is the current value + 1 (and than reset the timers to catch stalled topics).

**Comment by clalancette** [comment]
Given that we merged #461 , I'm going to go ahead and close this.  If you think this was in error, please feel free to reopen.
