### ISSUE TITLE
glibc-2.34 compatibility: __malloc_hook was removed

### ISSUE THREAD

**Issue by shr-project** [ros2/demos#530]
As https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html says:

> The deprecated memory allocation hooks __malloc_hook, __realloc_hook,
  __memalign_hook and __free_hook are now removed from the API.  Compatibility
  symbols are present to support legacy programs but new applications can no
  longer link to these symbols.  These hooks no longer have any effect on glibc
  functionality.  The malloc debugging DSO libc_malloc_debug.so currently
  supports hooks and can be preloaded to get this functionality back for older
  programs.  However this is a transitional measure and may be removed in a
  future release of the GNU C Library.  Users may port away from these hooks by
  writing and preloading their own malloc interposition library.

But https://github.com/ros2/demos/blob/master/pendulum_control/src/pendulum_demo.cpp still depends on it and `#pragma GCC diagnostic ignored "-Wdeprecated-declarations"` won't be enough this time

**Comment by clalancette** [comment]
We ended up "fixing" this in #544 , so closing this out.
