### ISSUE TITLE
showimage demo fails with OpenSplice

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/demos#79]
On Linux and OS X the test fails:
- http://ci.ros2.org/job/ci_linux/lastCompletedBuild/testReport/
- http://ci.ros2.org/job/ci_osx/lastCompletedBuild/testReport/

On Windows it fails to compile:
- http://ci.ros2.org/job/ci_windows/1659/console

**Comment by mikaelarguedas** [comment]
This test passed on [Windows](http://ci.ros2.org/job/ci_windows_opensplice67/8) and [Linux](http://ci.ros2.org/job/ci_linux/3193) on the latest jobs. Keeping it open until MacOS test pass as well

@dirk-thomas FYI

**Comment by dirk-thomas** [comment]
I will close this for now since the problem seems to be fixed on all the platforms we can currently test. If it happens to fail on OS X in the future we can reopen this.
